################################################################################
### Build System
################################################################################

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/circuit_benchmarks_guppy"]

################################################################################
### Project
################################################################################

[project]
name = "circuit-benchmarks-guppy"
version = "0.0.0"
description = "Quantum circuit benchmarks written in Guppy"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name = "Karl Mayer", email = "karl.mayer@quantinuum.com"}
]
maintainers = [
  {name = "Karl Mayer", email = "karl.mayer@quantinuum.com"}
]
classifiers = [
    "Private :: Do Not Upload",
]


################################################################################
### Dependencies
################################################################################

dependencies = [
    "guppylang>=0.20.0",
    "hugr>=0.12.5",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "scipy>=1.16.0",
]

[project.optional-dependencies]

[dependency-groups]
dev = [
    "pylint>=3.3.7",
]
notebooks = [
    "ipykernel>=6.29.5",
]
sim = [
    "selene-sim>=0.2.0rc1",
]
hardware = [
    "qnexus>=0.22.0",
]
docs = [
    "furo>=2024.8.6",
    "ipython>=9.4.0",
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.6",
    "nbsphinx-link>=1.3.1",
    "pylint>=3.3.7",
    "pypandoc>=1.15",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-design>=0.6.1",
    "sphinxcontrib-plantuml>=0.30",
]


################################################################################
### Tools
################################################################################

[tool.uv]
package = true
default-groups = [
    "dev",
    "notebooks", 
    "sim", 
    "hardware",
]

[tool.pyright]
typeCheckingMode = "off"
