################################################################################
### Build System
################################################################################

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/circuit_benchmarks_guppy"]

################################################################################
### Project
################################################################################

[project]
name = "circuit-benchmarks-guppy"
version = "0.0.0"
description = "Quantum circuit benchmarks written in Guppy"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name = "Karl Mayer", email = "karl.mayer@quantinuum.com"}
]
maintainers = [
  {name = "Karl Mayer", email = "karl.mayer@quantinuum.com"}
]
classifiers = [
    "Private :: Do Not Upload",
]


################################################################################
### Dependencies
################################################################################

dependencies = [
    "guppylang>=0.20.0",
    "hugr>=0.12.5",
    "matplotlib>=3.10.3",
    "msgpack>=1.1.1",
    "numpy>=2.3.1",
    "scipy>=1.16.0",
]


[project.optional-dependencies]

[dependency-groups]
# Default dev groups
dev = [
    { include-group = "lint" },
    { include-group = "notebooks" },
    { include-group = "sim" },
    { include-group = "hardware" },
    { include-group = "test" },
]
lint = [
    "pylint>=3.3.7",
]
notebooks = [
    "ipykernel>=6.29.5",
]
sim = [
    "selene-sim>=0.2.0"
]
hardware = [
    "qnexus>=0.22.0",
]
test = [
    "pytest>=8.4.1",
]

# Optional groups
docs = [
    "furo>=2024.8.6",
    "ipython>=9.4.0",
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.6",
    "nbsphinx-link>=1.3.1",
    "pylint>=3.3.7",
    "pypandoc>=1.15",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-design>=0.6.1",
    "sphinxcontrib-plantuml>=0.30",
]
#sim_noise = [
#    "selene-anduril-plugin",
#    "pecos-selene",
#    "selene_custom_error_model"
#]


################################################################################
### Tools
################################################################################

[tool.uv]
package = true

#[[tool.uv.index]]
#name = "quantinuumsw"
#url = "https://quantinuumsw.jfrog.io/artifactory/api/pypi/pypi_local/simple"
#explicit = true

#[tool.uv.sources]
#selene-anduril-plugin = { index = "quantinuumsw" }
#pecos-selene = { index = "quantinuumsw" }
#selene_custom_error_model = { index = "quantinuumsw" }


[tool.pyright]
typeCheckingMode = "off"


[tool.pytest.ini_options]
markers = [
    "slow_sim: marks tests as slow_sim (deselect with '-m \"not slow_sim\"')",
]
